spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.62:3306/sell?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.100.62
    port: 6379
#server:
#  context-path: /sell


weChat:
#  mpAppId: wxd898fcb01713c658 支付appid
  mpAppId: wx24edd7196ea7e8a4
  mpAppSecret: 41f98730ba5615a9f8888fbf2c9bde77
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://hjx.natapp1.cc/notify


